Implemented Typescript
ynnoj/next-stripe pull request #26
Opened 2021-04-14 19:41 UTC by NishargShah

1. Implemented all code into Typescript
2. Added `Next.Js` as Dependency and `prettier, @types/react and @types/react-dom` as Dev Dependency
3. Root `client.js` and `index.js` changed a little bit.
4. Added `apiVersion` in every file for `stripe`
5. You can remove babel if you want.

2021-04-15 05:09 UTC, NishargShah commented
I try to solve one problem but I am not getting the clue why its coming

```
message: "You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/."
status: 401
```

If I replace the import with typescript support library it's giving me the above error when I try to access 

```
stripe.checkout.sessions.create(req.body)
```

but if I replace import with the current `beta-9` version all will be fixed, I don't understand why??

can you please guide me where I am wrong @ynnoj

2021-04-17 21:00 UTC, NishargShah commented
> I try to solve one problem but I am not getting the clue why its coming
> 
> ```
> message: "You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/."
> status: 401
> ```
> 
> If I replace the import with typescript support library it's giving me the above error when I try to access
> 
> ```
> stripe.checkout.sessions.create(req.body)
> ```
> 
> but if I replace import with the current `beta-9` version all will be fixed, I don't understand why??
> 
> can you please guide me where I am wrong @ynnoj

Solved it

2021-04-17 21:15 UTC, NishargShah commented
@ynnoj can you please review it and merge it

2021-08-11 06:16 UTC, NishargShah commented
xDD, I used it in my 2 projects and started the 3rd project and I thought why is it not in TS and I checked this PR still not merged, please do it ASAP, so we get clear IDE IntelliSense.

2021-12-24 10:43 UTC, baptisteArno commented
Are you still maintaining this repo @ynnoj?

2021-12-24 10:53 UTC, baptisteArno requested changes

2021-12-24 10:53 UTC, baptisteArno commented on babel.config.json
> -}
I think we should keep babel to build the project. It needs to use [preset/typescript](https://babeljs.io/docs/en/babel-preset-typescript)

2021-12-24 10:53 UTC, baptisteArno commented on package.json
> -    "watch": "babel --watch src --out-dir dist"
Keep babel

2022-10-16 12:14 UTC, merged